# Generated by Django 4.0.1 on 2022-02-01 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, verbose_name="Species code"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        max_length=200, verbose_name="Species code"
                    ),
                ),
                (
                    "vernacular_name",
                    models.CharField(
                        max_length=200, verbose_name="Species code"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "Valide"), ("FREEZE", "Gelée")],
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mortality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "date_mortality",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Mortality observation date",
                    ),
                ),
                (
                    "nb_death",
                    models.IntegerField(
                        default=1, verbose_name="Number found dead"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Author of the mortality observation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mortality_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author of the mortality observation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mortality data source",
                        limit_choices_to={"type__mnemonic": "organism"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_data_source",
                        to="sinp_nomenclatures.item",
                        verbose_name="Mortality data source",
                    ),
                ),
                (
                    "death_cause",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cause of death",
                        limit_choices_to={"type__mnemonic": "cause_of_death"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                        verbose_name="Cause of death",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Media related to the mortality case",
                        related_name="mortality_media",
                        to="media.Media",
                        verbose_name="Media related to the mortality case",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Species",
                        limit_choices_to={"type__mnemonic": "species"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="species_name",
                        to="sinp_nomenclatures.item",
                        verbose_name="Species",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
