# Generated by Django 4.0.1 on 2022-02-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("species", "0001_initial"),
        ("mortality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortality",
            name="species",
            field=models.ForeignKey(
                help_text="Found dead species",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_species",
                to="species.species",
                verbose_name="Found dead species",
            ),
        ),
        migrations.AddField(
            model_name="mortality",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
