# Generated by Django 4.0.1 on 2022-02-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("mortality", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mortality",
            old_name="date_mortality",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="mortality",
            name="death_cause",
            field=models.ForeignKey(
                help_text="Cause of death",
                limit_choices_to={"type__mnemonic": "cause_of_death"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_cod",
                to="sinp_nomenclatures.item",
                verbose_name="Cause of death",
            ),
        ),
        migrations.AlterField(
            model_name="mortality",
            name="species",
            field=models.ForeignKey(
                help_text="Found dead species",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_species",
                to="mortality.species",
                verbose_name="Found dead species",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="status",
            field=models.ForeignKey(
                help_text="Species activated status",
                limit_choices_to={"type__mnemonic": "activated_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="species_activated_status",
                to="sinp_nomenclatures.item",
                verbose_name="Species activated status",
            ),
        ),
    ]
