# Generated by Django 4.0.1 on 2022-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("mortality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortality",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media related to the mortality case",
                related_name="mortality_media",
                to="media.Media",
                verbose_name="Media related to the mortality case",
            ),
        ),
    ]
