# Generated by Django 4.0.1 on 2022-01-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mortality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mortality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "nb_death",
                    models.IntegerField(
                        default=1, verbose_name="Number found dead"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mortality data source",
                        limit_choices_to={
                            "type__mnemonic": "death_data_source"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortality_data_source",
                        to="sinp_nomenclatures.item",
                        verbose_name="Mortality data source",
                    ),
                ),
                (
                    "death_cause",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cause of death",
                        limit_choices_to={"type__mnemonic": "death_cause"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                        verbose_name="Cause of death",
                    ),
                ),
                (
                    "pictures",
                    models.ManyToManyField(
                        help_text="Segment attached with this observation",
                        related_name="mortality_pictures",
                        to="media.Picture",
                        verbose_name="Segment attached with this observation",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Species",
                        limit_choices_to={"type__mnemonic": "species"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="species_name",
                        to="sinp_nomenclatures.item",
                        verbose_name="Species",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Case",
        ),
    ]
