# Generated by Django 4.0.1 on 2022-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mortality", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortality",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Author"),
        ),
    ]
