# Generated by Django 4.0.1 on 2022-02-03 09:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mortality", "0005_alter_mortality_options_mortality_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mortality",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
