# Generated by Django 4.0.1 on 2022-02-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0002_initial"),
        ("mortality", "0006_alter_mortality_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortality",
            name="infrstr",
            field=models.ForeignKey(
                blank=True,
                help_text="Infrastructure related to mortality case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mortality_infrstr",
                to="cables.infrastructure",
                verbose_name="Infrastructure related to mortality case",
            ),
        ),
    ]
