# Generated by Django 4.0.1 on 2022-02-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mortality", "0008_rename_geom_mortality_mort_geom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mortality",
            old_name="mort_geom",
            new_name="geom",
        ),
    ]
