FROM node:lts

WORKDIR /app

RUN apt update && apt upgrade -y
RUN apt install -y git

COPY ./package*.json /app/

RUN npm install && npm cache clean --force

COPY . .

ENV PATH ./node_modules/.bin/:$PATH
