## Build
FROM node:lts-alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install -g npm@latest & npm install
COPY . ./
RUN npm run build

EXPOSE 3000

# VOLUME ["/app"]
