# Generated by Django 4.0.1 on 2022-01-11 08:58

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "sa_name",
                    models.CharField(
                        error_messages={
                            "unique": "A sensible area with that name already exists."
                        },
                        help_text="Required. 200 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="sensible area name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sensitivity_level",
                    models.ForeignKey(
                        help_text="Sensitivity level of the area",
                        limit_choices_to={
                            "type__mnemonic": "area_sensitivity_level"
                        },
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                        verbose_name="Level of area sensitivity",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
