# Generated by Django 4.0.3 on 2023-05-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_content', '0002_alter_partners_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Contenu privé'),
        ),
    ]
