# Generated by Django 4.0.1 on 2022-01-11 08:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remark"
                    ),
                ),
                (
                    "neutralized",
                    models.BooleanField(
                        default=False, verbose_name="Neutralized"
                    ),
                ),
                (
                    "isolation_advice",
                    models.BooleanField(
                        default=False, verbose_name="Isolation"
                    ),
                ),
                (
                    "dissuasion_advice",
                    models.BooleanField(
                        default=False, verbose_name="Dissuasion"
                    ),
                ),
                (
                    "attraction_advice",
                    models.BooleanField(
                        default=False, verbose_name="Attraction"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remark"
                    ),
                ),
                (
                    "neutralized",
                    models.BooleanField(
                        default=False, verbose_name="Neutralized"
                    ),
                ),
                (
                    "building_integration_risk",
                    models.ForeignKey(
                        help_text="Level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                        verbose_name="Level of risk",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moving_risk",
                    models.ForeignKey(
                        help_text="Level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                        verbose_name="Level of risk",
                    ),
                ),
                (
                    "pole_condition",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                    ),
                ),
            ],
        ),
    ]
