# Generated by Django 4.0.1 on 2022-01-26 11:16

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "__first__"),
        ("sensitive_area", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("geo_area", "0002_alter_geoarea_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Administrative and Natural Areas",
                        related_name="%(class)s_geo_area",
                        to="geo_area.GeoArea",
                        verbose_name="Associated Administrative and Natural Areas",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Infrastructure owner organism",
                        limit_choices_to={"type__mnemonic": "organism"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owner",
                        to="sinp_nomenclatures.item",
                        verbose_name="Infrastructure owner organism",
                    ),
                ),
                (
                    "sensitivity_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Sensitivity Areas",
                        related_name="%(class)s_sensitive_area",
                        to="sensitive_area.SensitiveArea",
                        verbose_name="Associated Sensitivity Areas",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geo_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Administrative and Natural Areas",
                        related_name="%(class)s_geo_area",
                        to="geo_area.GeoArea",
                        verbose_name="Associated Administrative and Natural Areas",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Infrastructure owner organism",
                        limit_choices_to={"type__mnemonic": "organism"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_owner",
                        to="sinp_nomenclatures.item",
                        verbose_name="Infrastructure owner organism",
                    ),
                ),
                (
                    "sensitivity_area",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated Sensitivity Areas",
                        related_name="%(class)s_sensitive_area",
                        to="sensitive_area.SensitiveArea",
                        verbose_name="Associated Sensitivity Areas",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="unique Id",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Visit date",
                    ),
                ),
                (
                    "visit",
                    models.TextField(
                        blank=True, null=True, verbose_name="Visit"
                    ),
                ),
                (
                    "neutralized",
                    models.BooleanField(
                        default=False, verbose_name="Neutralized"
                    ),
                ),
                (
                    "isolation_advice",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Isolation"
                    ),
                ),
                (
                    "dissuasion_advice",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Dissuasion"
                    ),
                ),
                (
                    "attraction_advice",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Attraction"
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Pole condition",
                        limit_choices_to={
                            "type__mnemonic": "infrastr_condition"
                        },
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_condition",
                        to="sinp_nomenclatures.item",
                        verbose_name="Pole condition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Media attached with this visit",
                        related_name="visit_media",
                        to="media.Media",
                        verbose_name="Media attached with this visit",
                    ),
                ),
                (
                    "pole",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pole attached with this visit",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_pole",
                        to="cables.pole",
                        verbose_name="Pole attached with this visit",
                    ),
                ),
                (
                    "pole_attractivity",
                    models.ForeignKey(
                        help_text="Attractivity level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_attractivity",
                        to="sinp_nomenclatures.item",
                        verbose_name="Attractivity level of risk",
                    ),
                ),
                (
                    "pole_dangerousness",
                    models.ForeignKey(
                        help_text="dangerousness level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_dangerousness",
                        to="sinp_nomenclatures.item",
                        verbose_name="dangerousness level of risk",
                    ),
                ),
                (
                    "pole_type_primary",
                    models.ForeignKey(
                        help_text="Primary pole type",
                        limit_choices_to={"type__mnemonic": "pole_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_type_primary",
                        to="sinp_nomenclatures.item",
                        verbose_name="Primary pole type",
                    ),
                ),
                (
                    "pole_type_secondary",
                    models.ForeignKey(
                        help_text="Secondary pole type",
                        limit_choices_to={"type__mnemonic": "pole_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pole_type_secondary",
                        to="sinp_nomenclatures.item",
                        verbose_name="Secondary pole type",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment attached with this visit",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cables.segment",
                        verbose_name="Segment attached with this visit",
                    ),
                ),
                (
                    "segt_build_integr_risk",
                    models.ForeignKey(
                        help_text="Building integration level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_building_integration_risk",
                        to="sinp_nomenclatures.item",
                        verbose_name="Building integration level of risk",
                    ),
                ),
                (
                    "segt_moving_risk",
                    models.ForeignKey(
                        help_text="moving level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_moving_risk",
                        to="sinp_nomenclatures.item",
                        verbose_name="moving level of risk",
                    ),
                ),
                (
                    "sgmt_topo_integr_risk",
                    models.ForeignKey(
                        help_text="Topological level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_topological_integration_risk",
                        to="sinp_nomenclatures.item",
                        verbose_name="topological level of risk",
                    ),
                ),
                (
                    "sgmt_veget_integr_risk",
                    models.ForeignKey(
                        help_text="vegetation level of risk",
                        limit_choices_to={"type__mnemonic": "risk_level"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segment_vegetation_risk",
                        to="sinp_nomenclatures.item",
                        verbose_name="vegetation level of risk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="unique Id",
                    ),
                ),
                (
                    "installed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Installed"
                    ),
                ),
                (
                    "pole_nb_equipments",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of equipments"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "eqmt_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of equipment for pole",
                        limit_choices_to={"type__mnemonic": "equipment_type"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_pole_eqmt_type",
                        to="sinp_nomenclatures.item",
                        verbose_name="Type of equipment for pole",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Media attached with this equipment",
                        related_name="equipment_media",
                        to="media.Media",
                        verbose_name="Media attached with this equipment",
                    ),
                ),
                (
                    "pole",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pole the equipment is installed on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_pole",
                        to="cables.pole",
                        verbose_name="Pole the equipment is installed on",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment the equipment is installed on",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_segment",
                        to="cables.segment",
                        verbose_name="Segment the equipment is installed on",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("pole__isnull", False), ("segment__isnull", True)
                    ),
                    models.Q(
                        ("pole__isnull", True), ("segment__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="cables_visit_only_one_of_both_field_not_null_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("pole__isnull", False), ("segment__isnull", True)
                    ),
                    models.Q(
                        ("pole__isnull", True), ("segment__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="cables_equipment_only_one_infrastructure_constraint",
            ),
        ),
    ]
