# Generated by Django 4.0.1 on 2022-01-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cables", "0001_initial"),
        ("sensitive_area", "0001_initial"),
        ("media", "0001_initial"),
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("geo_area", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="geo_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Administrative and Natural Areas",
                related_name="%(class)s_geo_area",
                to="geo_area.GeoArea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="owner",
            field=models.ForeignKey(
                help_text="Infrastructure owner",
                limit_choices_to={"type__mnemonic": "owner"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_owner",
                to="sinp_nomenclatures.item",
                verbose_name="Infrastructure owner",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="sensitive_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Sensitivity Areas",
                related_name="%(class)s_sensitive_area",
                to="sensitive_area.SensitiveArea",
                verbose_name="Associated Sensitivity Areas",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="geo_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Administrative and Natural Areas",
                related_name="%(class)s_geo_area",
                to="geo_area.GeoArea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="owner",
            field=models.ForeignKey(
                help_text="Infrastructure owner",
                limit_choices_to={"type__mnemonic": "owner"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_owner",
                to="sinp_nomenclatures.item",
                verbose_name="Infrastructure owner",
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="sensitive_area",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated Sensitivity Areas",
                related_name="%(class)s_sensitive_area",
                to="sensitive_area.SensitiveArea",
                verbose_name="Associated Sensitivity Areas",
            ),
        ),
        migrations.AddField(
            model_name="pole",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="eqmt_type",
            field=models.ForeignKey(
                help_text="Type of operation for pole",
                limit_choices_to={"type__mnemonic": "operation_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_pole_eqmt_type",
                to="sinp_nomenclatures.item",
                verbose_name="Type of operation for pole",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this operation",
                related_name="operation_media",
                to="media.Media",
                verbose_name="Media attached with this operation",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="pole",
            field=models.ForeignKey(
                blank=True,
                help_text="Pole the operation is related to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_pole",
                to="cables.pole",
                verbose_name="Pole the operation is related to",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment the operation is related to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_segment",
                to="cables.segment",
                verbose_name="Segment tthe operation is related to",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("pole__isnull", False), ("segment__isnull", True)
                    ),
                    models.Q(
                        ("pole__isnull", True), ("segment__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="cables_visit_only_one_of_both_field_not_null_constraint",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("pole__isnull", False), ("segment__isnull", True)
                    ),
                    models.Q(
                        ("pole__isnull", True), ("segment__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="cables_operation_only_one_infrastructure_constraint",
            ),
        ),
    ]
