# Generated by Django 4.0.1 on 2022-01-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pole",
            old_name="sensitivity_area",
            new_name="sensitive_area",
        ),
        migrations.RenameField(
            model_name="segment",
            old_name="sensitivity_area",
            new_name="sensitive_area",
        ),
    ]
