# Generated by Django 4.0.1 on 2022-01-10 09:01

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polemodel",
            name="neutralized",
            field=models.BooleanField(
                default=False, verbose_name="Neutralisé"
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="neutralized",
            field=models.BooleanField(
                default=False, verbose_name="Neutralisé"
            ),
        ),
        migrations.CreateModel(
            name="SensibleArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                (
                    "sa_name",
                    models.CharField(
                        error_messages={
                            "unique": "A sensible area with that name already exists."
                        },
                        help_text="Required. 200 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="sensible area name",
                    ),
                ),
                (
                    "sensibility_level",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sinp_nomenclatures.item",
                    ),
                ),
            ],
        ),
    ]
