# Generated by Django 4.0.1 on 2022-03-01 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="condition",
            field=models.ForeignKey(
                help_text="Pole condition",
                limit_choices_to={"type__mnemonic": "infrastr_condition"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_condition",
                to="sinp_nomenclatures.item",
                verbose_name="Pole condition",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_attractivity",
            field=models.ForeignKey(
                help_text="Attractivity level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_attractivity",
                to="sinp_nomenclatures.item",
                verbose_name="Attractivity level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_dangerousness",
            field=models.ForeignKey(
                help_text="dangerousness level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_dangerousness",
                to="sinp_nomenclatures.item",
                verbose_name="dangerousness level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_type",
            field=models.ManyToManyField(
                help_text="Type of pole",
                limit_choices_to={"type__mnemonic": "pole_type"},
                null=True,
                related_name="visit_pole_type",
                to="sinp_nomenclatures.Item",
                verbose_name="Type of pole",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_build_integr_risk",
            field=models.ForeignKey(
                help_text="Building integration level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_building_integration_risk",
                to="sinp_nomenclatures.item",
                verbose_name="Building integration level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_moving_risk",
            field=models.ForeignKey(
                help_text="moving level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_moving_risk",
                to="sinp_nomenclatures.item",
                verbose_name="moving level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_topo_integr_risk",
            field=models.ForeignKey(
                help_text="Topological level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_topological_integration_risk",
                to="sinp_nomenclatures.item",
                verbose_name="topological level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_veget_integr_risk",
            field=models.ForeignKey(
                help_text="vegetation level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_vegetation_risk",
                to="sinp_nomenclatures.item",
                verbose_name="vegetation level of risk",
            ),
        ),
    ]
