# Generated by Django 4.0.1 on 2022-01-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "cables",
            "0002_polemodel_neutralized_segmentmodel_neutralized_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="polemodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sensiblearea",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="polemodel",
            name="neutralized",
            field=models.BooleanField(
                default=False, verbose_name="Neutralized"
            ),
        ),
        migrations.AlterField(
            model_name="polemodel",
            name="remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Remark"
            ),
        ),
        migrations.AlterField(
            model_name="segmentmodel",
            name="neutralized",
            field=models.BooleanField(
                default=False, verbose_name="Neutralized"
            ),
        ),
        migrations.AlterField(
            model_name="segmentmodel",
            name="remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Remark"
            ),
        ),
    ]
