# Generated by Django 4.0.1 on 2022-02-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="infrastructure",
            field=models.ForeignKey(
                help_text="Infrastructure attached with this Action",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions_infrastructure",
                to="cables.infrastructure",
                verbose_name="Infrastructure attached with this Action",
            ),
        ),
    ]
