# Generated by Django 4.0.1 on 2022-01-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="visit",
        ),
        migrations.AddField(
            model_name="visit",
            name="remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Remarks"
            ),
        ),
    ]
