# Generated by Django 4.0.1 on 2022-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="history",
            field=models.BooleanField(default=False, verbose_name="History"),
        ),
    ]
