# Generated by Django 4.0.3 on 2022-03-12 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0003_rename_item_nomenclature"),
        ("cables", "0002_alter_diagnosis_attraction_advice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_attractivity",
            field=models.ForeignKey(
                blank=True,
                help_text="Attractivity level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_attractivity",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Attractivity level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_dangerousness",
            field=models.ForeignKey(
                blank=True,
                help_text="dangerousness level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_dangerousness",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="dangerousness level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_build_integr_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="Building integration level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_building_integration_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="Building integration level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_moving_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="moving level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_moving_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="moving level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_topo_integr_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="Topological level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_topological_integration_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="topological level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="sgmt_veget_integr_risk",
            field=models.ForeignKey(
                blank=True,
                help_text="vegetation level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="segment_vegetation_risk",
                to="sinp_nomenclatures.nomenclature",
                verbose_name="vegetation level of risk",
            ),
        ),
    ]
