# Generated by Django 4.0.1 on 2022-01-18 13:05

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipment",
            name="cables_equipment_only_type_of_infrastructure_equipment_constraint",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="pole_eqmt_type",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="sgmt_eqmt_type",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="inventory_date",
        ),
        migrations.AddField(
            model_name="equipment",
            name="eqmt_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of equipment for pole",
                limit_choices_to={"type__mnemonic": "equipment_type"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment_pole_eqmt_type",
                to="sinp_nomenclatures.item",
                verbose_name="Type of equipment for pole",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 18, 14, 5, 46, 806399),
                editable=False,
            ),
        ),
    ]
