# Generated by Django 4.0.1 on 2022-01-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0003_alter_equipment_equipment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="equipment_date",
        ),
    ]
