# Generated by Django 4.0.1 on 2022-01-13 14:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0003_observation_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 12, 54, 626773),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="inventory_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 12, 54, 625264),
                editable=False,
                verbose_name="Inventory date",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="observation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 12, 54, 625278),
                verbose_name="Observation date",
            ),
        ),
    ]
