# Generated by Django 4.0.3 on 2022-03-25 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0003_alter_action_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infrastructure",
            options={"ordering": ["-id"]},
        ),
    ]
