# Generated by Django 4.0.1 on 2022-01-18 13:20

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cables",
            "0003_remove_equipment_cables_equipment_only_type_of_infrastructure_equipment_constraint_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 18, 14, 20, 28, 874536),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="segment",
            field=models.ForeignKey(
                help_text="Segment the equipment is installed on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_segment",
                to="cables.segment",
                verbose_name="Segment the equipment is installed on",
            ),
        ),
    ]
