# Generated by Django 4.0.3 on 2022-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0003_alter_diagnosis_pole_attractivity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="attraction_advice",
            field=models.BooleanField(
                default=False, verbose_name="Attraction"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="dissuasion_advice",
            field=models.BooleanField(
                default=False, verbose_name="Disruption"
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="isolation_advice",
            field=models.BooleanField(default=False, verbose_name="Isolation"),
        ),
    ]
