# Generated by Django 4.0.1 on 2022-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0003_action_history"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visit",
            new_name="Diagnosis",
        ),
        migrations.RenameModel(
            old_name="Segment",
            new_name="Line",
        ),
        migrations.RenameModel(
            old_name="Pole",
            new_name="Point",
        ),
    ]
