# Generated by Django 4.0.1 on 2022-01-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cables",
            "0004_polemodel_updated_by_segmentmodel_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensiblearea",
            old_name="sensibility_level",
            new_name="sensitivity_level",
        ),
    ]
