# Generated by Django 4.0.1 on 2022-02-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0004_rename_visit_diagnosis_rename_segment_line_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosis",
            options={"verbose_name_plural": "Diagnosis"},
        ),
    ]
