# Generated by Django 4.0.1 on 2022-01-13 14:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_area", "0001_initial"),
        ("sensitive_area", "0001_initial"),
        ("cables", "0004_alter_equipment_equipment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 25, 25, 384961),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="inventory_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 25, 25, 383449),
                editable=False,
                verbose_name="Inventory date",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="observation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 13, 15, 25, 25, 383464),
                verbose_name="Observation date",
            ),
        ),
        migrations.AlterField(
            model_name="pole",
            name="geo_area",
            field=models.ManyToManyField(
                blank=True,
                db_table="pole_geo_areas",
                help_text="Associated Administrative and Natural Areas",
                related_name="pole_geo_area",
                to="geo_area.GeoArea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
        migrations.AlterField(
            model_name="pole",
            name="sensitivity_areas",
            field=models.ManyToManyField(
                blank=True,
                db_table="pole_sensitive_areas",
                help_text="Associated Sensitivity Areas",
                related_name="pole_sensitive_area",
                to="sensitive_area.SensitiveArea",
                verbose_name="Associated Sensitivity Areas",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="geo_area",
            field=models.ManyToManyField(
                blank=True,
                db_table="sgmt_geo_areas",
                help_text="Associated Administrative and Natural Areas",
                related_name="sgmt_geo_area",
                to="geo_area.GeoArea",
                verbose_name="Associated Administrative and Natural Areas",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="sensitivity_areas",
            field=models.ManyToManyField(
                blank=True,
                db_table="sgmt_sensitive_areas",
                help_text="Associated Sensitivity Areas",
                related_name="sgmt_sensitive_area",
                to="sensitive_area.SensitiveArea",
                verbose_name="Associated Sensitivity Areas",
            ),
        ),
    ]
