# Generated by Django 4.0.1 on 2022-01-20 08:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("cables", "0005_alter_equipment_equipment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 20, 9, 59, 30, 68238),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this equipment",
                related_name="equipment_media",
                to="media.Media",
                verbose_name="Media attached with this equipment",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this visit",
                related_name="visit_media",
                to="media.Media",
                verbose_name="Media attached with this visit",
            ),
        ),
    ]
