# Generated by Django 4.0.1 on 2022-01-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0005_pole_owner_segment_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pole",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Infrastructure owner organism",
                limit_choices_to={"type__mnemonic": "infrastr_owner"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_owner",
                to="sinp_nomenclatures.item",
                verbose_name="Infrastructure owner organism",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Infrastructure owner organism",
                limit_choices_to={"type__mnemonic": "infrastr_owner"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_owner",
                to="sinp_nomenclatures.item",
                verbose_name="Infrastructure owner organism",
            ),
        ),
    ]
