# Generated by Django 4.0.1 on 2022-01-10 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        (
            "cables",
            "0005_rename_sensibility_level_sensiblearea_sensitivity_level",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SensibleArea",
            new_name="SensitiveArea",
        ),
    ]
