# Generated by Django 4.0.1 on 2022-01-28 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("media", "0001_initial"),
        ("cables", "0006_alter_visit_pole_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="condition",
            field=models.ForeignKey(
                help_text="Pole condition",
                limit_choices_to={"type__mnemonic": "infrastr_condition"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pole_condition",
                to="sinp_nomenclatures.item",
                verbose_name="Pole condition",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this visit",
                null=True,
                related_name="visit_media",
                to="media.Media",
                verbose_name="Media attached with this visit",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment attached with this visit",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_segment",
                to="cables.segment",
                verbose_name="Segment attached with this visit",
            ),
        ),
    ]
