# Generated by Django 4.0.1 on 2022-01-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0006_rename_sensiblearea_sensitivearea"),
    ]

    operations = [
        migrations.AddField(
            model_name="polemodel",
            name="sensitivity_areas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cables.sensitivearea",
                verbose_name="Related sensitive area",
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="sensitivity_areas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cables.sensitivearea",
                verbose_name="Related sensitive area",
            ),
        ),
    ]
