# Generated by Django 4.0.1 on 2022-01-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0007_alter_pole_owner_alter_segment_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pole",
            old_name="sensitivity_areas",
            new_name="sensitivity_area",
        ),
        migrations.RenameField(
            model_name="segment",
            old_name="sensitivity_areas",
            new_name="sensitivity_area",
        ),
    ]
