# Generated by Django 4.0.1 on 2022-01-20 09:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0007_alter_equipment_equipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 20, 10, 31, 53, 617713),
                editable=False,
            ),
        ),
    ]
