# Generated by Django 4.0.1 on 2022-01-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0007_polemodel_sensitivity_areas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentmodel",
            name="building_integration_risk",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="moving_risk",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="topological_integration_risk",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="vegetation_integration_risk",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
    ]
