# Generated by Django 4.0.1 on 2022-01-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0008_alter_visit_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="segt_build_integr_risk",
            new_name="sgmt_build_integr_risk",
        ),
        migrations.RenameField(
            model_name="visit",
            old_name="segt_moving_risk",
            new_name="sgmt_moving_risk",
        ),
    ]
