# Generated by Django 4.0.1 on 2022-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0008_alter_action_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="history",
        ),
        migrations.AddField(
            model_name="action",
            name="last",
            field=models.BooleanField(
                default=True, verbose_name="Last record"
            ),
        ),
    ]
