# Generated by Django 4.0.1 on 2022-01-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0008_segmentmodel_building_integration_risk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="polemodel",
            name="pole_condition",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
        migrations.AddField(
            model_name="segmentmodel",
            name="pole_condition",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
            ),
        ),
        migrations.AlterField(
            model_name="sensitivearea",
            name="sensitivity_level",
            field=models.ForeignKey(
                help_text="Sensitivity level of the area",
                limit_choices_to={"type__mnemonic": "sensitivity_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="area_sensitivity_level",
                to="sinp_nomenclatures.item",
                verbose_name="Level of area sensitivity",
            ),
        ),
    ]
