# Generated by Django 4.0.1 on 2022-01-20 10:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0008_alter_equipment_equipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 20, 11, 59, 54, 233520),
                editable=False,
            ),
        ),
    ]
