# Generated by Django 4.0.1 on 2022-01-31 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        (
            "cables",
            "0009_rename_segt_build_integr_risk_visit_sgmt_build_integr_risk_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="visit_date",
            new_name="operation_date",
        ),
        migrations.AlterField(
            model_name="operation",
            name="eqmt_type",
            field=models.ForeignKey(
                help_text="Type of operation for pole",
                limit_choices_to={"type__mnemonic": "equipment_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_pole_eqmt_type",
                to="sinp_nomenclatures.item",
                verbose_name="Type of operation for pole",
            ),
        ),
    ]
