# Generated by Django 4.0.1 on 2022-01-10 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        (
            "cables",
            "0009_polemodel_pole_condition_segmentmodel_pole_condition_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PoleModel",
            new_name="Pole",
        ),
        migrations.RenameModel(
            old_name="SegmentModel",
            new_name="Segment",
        ),
    ]
