# Generated by Django 4.0.1 on 2022-01-20 11:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0009_alter_equipment_equipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 20, 12, 30, 57, 983646),
                editable=False,
            ),
        ),
    ]
