# Generated by Django 4.0.1 on 2022-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0010_alter_diagnosis_pole_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                help_text="Media attached with this diagnosis",
                related_name="diagnosis_media",
                to="media.Media",
                verbose_name="Media attached with this diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="pole_type",
            field=models.ManyToManyField(
                blank=True,
                help_text="Type of pole",
                limit_choices_to={"type__mnemonic": "pole_type"},
                related_name="diagnosis_pole_type",
                to="sinp_nomenclatures.Item",
                verbose_name="Type of pole",
            ),
        ),
    ]
