# Generated by Django 4.0.1 on 2022-01-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("cables", "0010_rename_polemodel_pole_rename_segmentmodel_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="building_integration_risk",
            field=models.ForeignKey(
                help_text="Level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
                verbose_name="Level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="moving_risk",
            field=models.ForeignKey(
                help_text="Level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
                verbose_name="Level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="topological_integration_risk",
            field=models.ForeignKey(
                help_text="Level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
                verbose_name="Level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="vegetation_integration_risk",
            field=models.ForeignKey(
                help_text="Level of risk",
                limit_choices_to={"type__mnemonic": "risk_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
                verbose_name="Level of risk",
            ),
        ),
        migrations.AlterField(
            model_name="sensitivearea",
            name="sensitivity_level",
            field=models.ForeignKey(
                help_text="Sensitivity level of the area",
                limit_choices_to={"type__mnemonic": "area_sensitivity_level"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sinp_nomenclatures.item",
                verbose_name="Level of area sensitivity",
            ),
        ),
    ]
