# Generated by Django 4.0.1 on 2022-01-21 16:29

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0011_alter_equipment_equipment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 21, 17, 29, 12, 802707),
                editable=False,
            ),
        ),
    ]
