# Generated by Django 4.0.1 on 2022-01-10 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0013_species_mortalitycase"),
    ]

    operations = [
        migrations.AddField(
            model_name="pole",
            name="geocoord",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="geocoord",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
