# Generated by Django 4.0.1 on 2022-01-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cables", "0014_pole_geocoord_segment_geocoord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pole",
            old_name="geocoord",
            new_name="geom",
        ),
        migrations.RenameField(
            model_name="segment",
            old_name="geocoord",
            new_name="geom",
        ),
    ]
