# Generated by Django 4.0.1 on 2022-02-03 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Species code",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        max_length=200, verbose_name="Scientific name"
                    ),
                ),
                (
                    "vernacular_name",
                    models.CharField(
                        max_length=200, verbose_name="Vernacular name"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        help_text="Species activated status",
                        limit_choices_to={
                            "type__mnemonic": "activated_status"
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="species_activated_status",
                        to="sinp_nomenclatures.nomenclature",
                        verbose_name="Species activated status",
                    ),
                ),
            ],
        ),
    ]
