# Generated by Django 4.0.1 on 2022-02-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0002_remove_species_status_species_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name_plural": "Species"},
        ),
    ]
