# Generated by Django 4.0.1 on 2022-02-03 07:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="geo area name"
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        srid=4326
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Type of the geographical area",
                        limit_choices_to={"type__mnemonic": "geoarea_type"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geoarea_type",
                        to="sinp_nomenclatures.item",
                        verbose_name="Type of the geographical area",
                    ),
                ),
            ],
            options={
                "db_table": "geo_area",
                "unique_together": {("code", "name")},
            },
        ),
    ]
