# Generated by Django 4.0.3 on 2022-03-16 21:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo_area", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoarea",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                srid=4326
            ),
        ),
    ]
