# Generated by Django 4.0.1 on 2022-01-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinp_nomenclatures", "0002_alter_source_unique_together"),
        ("geo_area", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoarea",
            name="type",
            field=models.ForeignKey(
                help_text="Type of the geographical area",
                limit_choices_to={"type__mnemonic": "geoarea_type"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="geoarea_type",
                to="sinp_nomenclatures.item",
                verbose_name="Type of the geographical area",
            ),
        ),
    ]
