# Generated by Django 4.0.3 on 2022-03-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_create", models.DateTimeField(auto_now_add=True)),
                ("timestamp_update", models.DateTimeField(auto_now=True)),
                ("storage", models.ImageField(upload_to="uploads")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Author",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Source of data",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="Remark"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
