# Generated by Django 4.0.1 on 2022-02-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='storage',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
