# Generated by Django 4.0.1 on 2022-01-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
