# Generated by Django 4.0.1 on 2022-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="media",
            new_name="storage",
        ),
        migrations.RemoveField(
            model_name="media",
            name="added_by",
        ),
        migrations.AlterField(
            model_name="media",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
    ]
