# Generated by Django 4.0.1 on 2022-01-17 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cables", "0002_initial"),
        ("media", "0001_initial"),
        ("mortality", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="mortality",
            field=models.ForeignKey(
                blank=True,
                help_text="Mortality observation the media is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_mortality",
                to="mortality.mortality",
                verbose_name="Mortality observation the media is related to",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                help_text="Visit the media is related to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_visit",
                to="cables.visit",
                verbose_name="Visit the media is related to",
            ),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("mortality", False), ("visit", True)),
                    models.Q(
                        ("equipment", True),
                        ("mortality", False),
                        ("visit", False),
                    ),
                    models.Q(("mortality", True), ("visit", False)),
                    _connector="OR",
                ),
                name="Media_only_one_field_not_null_constraint",
            ),
        ),
    ]
