# Generated by Django 4.0.1 on 2022-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "media",
            "0002_rename_media_media_storage_remove_media_added_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="remark",
            field=models.TextField(
                blank=True, null=True, verbose_name="Remark"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="storage",
            field=models.ImageField(upload_to="uploads"),
        ),
    ]
