# Generated by Django 4.0.1 on 2022-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_media_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="media",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
