# Generated by Django 4.0.3 on 2022-03-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_area", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo_area.geoarea",
                verbose_name="Emprise géographique par défaut",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organism",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.organism",
                verbose_name="Organisme",
            ),
        ),
    ]
