# Generated by Django 4.0.3 on 2023-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_area_user_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Logo'),
        ),
    ]
